### ISSUE TITLE
Webロゴ掲載(Chatwork株式会社様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#121]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "",
 "logo": "",
 "url": "https://corp.chatwork.com/ja/"
}
```

ロゴ画像:https://drive.google.com/file/d/1t--gejggxNQg0vQMeWFxraqlpgFxMvTL/view?usp=sharing

**Comment by YumiShibazaki** [comment]
掲載完了しました。
