### ISSUE TITLE
Webロゴ掲載(マーベリック株式会社様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#123]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "",
 "logo": "",
 "url": "https://www.mvrck.co.jp/"
}
```
ロゴ画像:https://drive.google.com/file/d/1ZduPJIZtrXJdS2mghYoLAzzmu3r6umRl/view?usp=sharing

**Comment by YumiShibazaki** [comment]
掲載完了しました。
