### ISSUE TITLE
Webロゴ掲載(株式会社セプテーニ・オリジナル様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#124]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "",
 "logo": "",
 "url": "https://www.septeni-original.co.jp/"
}
```

ロゴ画像:https://drive.google.com/file/d/1w-khVUiGrh4aqriLzLzfZ15eUpFACWJM/view?usp=sharing

**Comment by YumiShibazaki** [comment]
掲載完了しました。
