### ISSUE TITLE
Webロゴ掲載(株式会社はてな様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#125]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "",
 "logo": "",
 "url": "http://hatenacorp.jp/"
}
```

ロゴ画像:https://drive.google.com/file/d/14moCYgsLYDwnETRlPBlfatM_OzvTSQB6/view?usp=sharing

**Comment by tomoco95** [comment]
@YumiShibazaki 新しいテンプレにアップデートしておきました。OPENになってる他のスポンサーロゴ掲載Issueも、これと同じ形に合わせて作業していってもらえたらいいかなと思います！

**Comment by YumiShibazaki** [comment]
掲載完了しました。
