### ISSUE TITLE
Webロゴ掲載(WAmazing株式会社様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#134]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "wamazing",
 "logo": "",
 "url": "https://hrmos.co/pages/wamazing/jobs/0000007"
}
```

ロゴ画像:https://drive.google.com/file/d/122DoS7b5aCLkiWdWS4kTdeZmR68NwbgR/view?usp=sharing

**Comment by YumiShibazaki** [comment]
掲載完了しました。
