### ISSUE TITLE
Webロゴ掲載(奉行スポンサー様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#135]
kintone、cacoo、Hatenaさんについて奉行スポンサーとしてWebサイトに載せます。

- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "kintone",
 "logo": "",
 "url": "https://kintone.cybozu.com/jp/"
}
,{
 "name": "cacoo",
 "logo": "",
 "url": "https://cacoo.com/"
}
,{
 "name": "hatena",
 "logo": "",
 "url": "http://hatenacorp.jp/"
}
```

ロゴ画像:
https://drive.google.com/file/d/1SbLa-Xp4IWoi6qMuhMDQrrZFkSNhzGOU/view?usp=sharing
https://drive.google.com/open?id=1RGe1jHXAQfACUDiO0u-64wXz3OIpGnCE
https://drive.google.com/file/d/14moCYgsLYDwnETRlPBlfatM_OzvTSQB6/view?usp=sharing

**Comment by tomoco95** [comment]
掲載されました

**Comment by YumiShibazaki** [comment]
cacooさんのロゴの余白を調整するため、reopenします。
調整後のロゴはこちら：https://drive.google.com/open?id=1VGsJ5UebJYFuAh1a55AWUrURo0pIMQCx

**Comment by YumiShibazaki** [comment]
cacooさんのロゴ、差し替え完了しました。=> #199 , #201
