### ISSUE TITLE
Webロゴ掲載(株式会社サムライズム(表示名は JetBrains s.r.o. でお願いいたします)様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#165]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [ ] develop branchに向けてPullRequestを送る
- [ ] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "",
 "logo": "",
 "url": "https://www.jetbrains.com/idea/"
}
```

ロゴ画像:https://drive.google.com/open?id=1_G-oZSx_mReWIMavXCB-K55999kcyDbD

**Comment by YumiShibazaki** [comment]
@tomoco95 
ロゴサイズが20:7になってなさそうです…。
サイズ調整お願いします。

**Comment by YumiShibazaki** [comment]
調整後のロゴはこちら：https://drive.google.com/open?id=1ImghvW1Dm0t0pwSCjUX1V54LQa7pD-xt

**Comment by tomoco95** [comment]
develop branchを他の開発で使用中だったため、今回はmasterにPullRequestを投げて対応しました。

**Comment by YumiShibazaki** [comment]
リンク先を下記に差し替えてほしいと連絡をいただいたので、Reopenします。

https://www.jetbrains.com/ja-jp/

**Comment by tomoco95** [comment]
リンク先を差し替えて、サムライズムさまへご連絡しました！
