### ISSUE TITLE
Webロゴ掲載(SUGAR株式会社様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#166]
- [x] リポジトリにロゴを入れる
- [ ] jsonファイルを変更する
- [ ] develop branchに向けてPullRequestを送る
- [ ] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "sugar",
 "logo": "",
 "url": "https://sugarcorp.jp/"
}
```

ロゴ画像:https://drive.google.com/file/d/1CdTSoHxbs6iXEg3zFD4lU_j7uzpaL7CO/view?usp=sharing

**Comment by YumiShibazaki** [comment]
develop branchを他の開発で使用中だったため、今回はmasterにPullRequestを投げて対応しました。( #172 )
