### ISSUE TITLE
企業ロゴの並びがシャッフルされるようにする(Shuffle the order of company logo images on top page)

### ISSUE THREAD

**Issue by sugoikondo** [scalamatsuri/2020.scalamatsuri.org#173]
現状だとトップの企業ロゴが表示時にランダムにシャッフルされないため、常に同じ順序で表示されてしまっている。

表示するごとに並びがランダムに入れ替わるようにする。

Currently the order of company logos are fixed, so add some codes to randomize its order.

(英語合ってるかな…)

**Comment by taisukeoe** [comment]
順番を入れ替えたい

## トップページ
### トップ上：将軍
### トップ下：将軍〜侍
https://scalamatsuri.org/ja/

## スポンサーページ
https://scalamatsuri.org/ja/sponsors/

**Comment by omiend** [comment]
https://github.com/scalamatsuri/2020.scalamatsuri.org/pull/186 で対応
