### ISSUE TITLE
Webロゴ掲載(株式会社grooves（webへの掲載はForkwell名義でお願いします）様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#185]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "",
 "logo": "",
 "url": "https://forkwell.com/"
}
```
ロゴ画像:https://drive.google.com/open?id=1yrNT8JyE6Msdctr9LX9_TKV3cDKalJwS

**Comment by taisukeoe** [comment]
#201 にて公開済み。
