### ISSUE TITLE
プロポーザルごとにパーマリンクを発行する

### ISSUE THREAD

**Issue by sugoikondo** [scalamatsuri/2020.scalamatsuri.org#207]
モーダルをフルスクリーンで表示する件の検討

## モチベーション(by @taisukeoe )
現在プロポーザルごとにパーマリンクが存在しないので、SNSで共有することが難しい。
今後、選考委員による選考などでも、パーマリンクがあった方がなにかと便利である。

**Comment by taisukeoe** [comment]
プロポーザル一覧ページの `tableRow.vue` でidを設定するようにして、以下のようにプロポーザルのリンクを発行するのが一番楽かもしれない

https://scalamatsuri.org/ja/proposals/#E1

[参考JSON](https://script.googleusercontent.com/macros/echo?user_content_key=mfBB8AXoJzzF5LwKoyfddfdQCjAGuqMSC3crN5NCyDAnUIDuEKqrOzlojyI1Im1Piv60lfSsipp2xndyToIfShWuMESSloo6m5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnCG6YRGkwakYiM4g7QSD71yor-SUcUsbgCEu6y8OwwJWsclhbf029at7oLAvt1I8H8Tvy1m0tLyP&lib=MisilZSAlQJ8rXqHk1xRP1rlCWkN5VxJb)

**Comment by taisukeoe** [comment]
マウスオーバーじゃなくても良いですが、tableRow(以下のSS参照)のどこかにidのリンクは欲しいですね

<img width="1017" alt="スクリーンショット 2020-01-25 14 57 39" src="https://user-images.githubusercontent.com/1506707/73117019-18f20000-3f83-11ea-8556-2d182b68b630.png">

リンクのイメージは、こんな感じ
<img width="206" alt="スクリーンショット 2020-01-25 14 56 00" src="https://user-images.githubusercontent.com/1506707/73117009-d3353780-3f82-11ea-9091-7c47951fce32.png">

**Comment by omiend** [comment]
個別ページを作ってしまっても良いかなと思いました。
とりあえずPR作りご意見伺います！（対応中）

**Comment by omiend** [comment]
![licecap](https://user-images.githubusercontent.com/4135267/75007373-41084c80-54b8-11ea-80fa-c575ca15248b.gif)
