### ISSUE TITLE
チェックインコードを入力し、保存できる

### ISSUE THREAD

**Issue by taisukeoe** [scalamatsuri/2020.scalamatsuri.org#219]
## 背景
ScalaMatsuriのCFP 投票は、チケット購入者、スポンサー招待枠行使者、およびスタッフが可能であり、それぞれに対し一意なチェックインコードが割り振られ、通知される。

## 必要な機能
チェックインコードを、プロポーザル画面で登録可能な機能が必要。

## 使い道
投票終了後に投票結果を集計する際に、有効なチェックインコードが登録されているものだけにフィルタする。

## 参考
チェックインコードを使った投票フロー
https://blog.scalamatsuri.org/entry/2019/02/20/120550

デザイン画像
![image](https://user-images.githubusercontent.com/1506707/73118324-f7e6da80-3f95-11ea-9fd8-131f85e08080.png)

**Comment by sugoikondo** [comment]
メモ: チェックインコードの編集について

<img width="1271" alt="Proposals___The_largest_international_Scala_conference_in_Asia" src="https://user-images.githubusercontent.com/16359063/73118357-6af05100-3f96-11ea-9c06-73165b3f4416.png">

チェックインコードを誤って入力した際に編集できないとまずいので、上部のログイン済みの際にでる箇所に『チェックインコードを入力』みたいなボタンを設ける。
それをクリックすると、モーダルが開くようにする。

**Comment by taisukeoe** [comment]
登録、編集、Cloud Firestoreへの保存を確認しました。
