### ISSUE TITLE
Webロゴ掲載(Fringe81株式会社様) 

### ISSUE THREAD

**Issue by YumiShibazaki** [scalamatsuri/2020.scalamatsuri.org#243]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "Fringe81株式会社",
 "logo": "",
 "url": "https://www.fringe81.com/join/engineer/"
}
```
ロゴ画像:https://drive.google.com/open?id=1HdW1c659O4yDliHXaBcQVU5ZasOrHW3S

**Comment by tomoco95** [comment]
#244 にて掲載しました！

**Comment by YumiShibazaki** [comment]
掲載完了しました。=> #244 , #246

**Comment by YumiShibazaki** [comment]
掲載完了しました。=> #244 , #246
