### ISSUE TITLE
CFP応募フォームの旅費助成金の説明がリンク切れ

### ISSUE THREAD

**Issue by exoego** [scalamatsuri/2020.scalamatsuri.org#253]
[こちらの応募フォーム](https://docs.google.com/forms/d/e/1FAIpQLSeEg5gTdMG631gN8lJ6xJ89-ZtCK928_bUJT2uA_wWqASOm5Q/viewform)にて、

* `http://2020.scalamatsuri.org/ja/cfp/#旅費助成金 )をご確認下さい。` というリンクになってしまっているようです。
* また URL を削って  http://2020.scalamatsuri.org/ja/cfp/#旅費助成金 を開いても、https://scalamatsuri.org/ja/cfp/ にリダイレクトされていまい、旅費助成金のところにジャンプしないようです

![image](https://user-images.githubusercontent.com/127635/73543482-633f1980-447a-11ea-8eee-393a55d5d200.png)

**Comment by taisukeoe** [comment]
ご報告ありがとうございます。

ひとまず該当リンクを有効なものに修正しました。
<img width="675" alt="スクリーンショット 2020-02-01 11 51 06" src="https://user-images.githubusercontent.com/1506707/73585890-30803a00-44e9-11ea-8782-5909851d6ef6.png">

**Comment by taisukeoe** [comment]
リンク切れ問題は解決した一方で、`#旅費助成金` や `#trave-grant` だけでなく、リニューアル後Webサイト全体で、要素のidをあまり振っていない、という問題がありそうです。

そちらは別issueで対応していきましょう。

**Comment by taisukeoe** [comment]
#269 へ委譲しました
