### ISSUE TITLE
プロポーザル修正依頼まとめ

### ISSUE THREAD

**Issue by Iwaji** [scalamatsuri/2020.scalamatsuri.org#290]
プロポーザルの修正依頼をいただいたものをまとめていきます。

**Comment by Iwaji** [comment]
Mikhail Limanskiyさんの[250](https://github.com/scalamatsuri/2020.scalamatsuri.org/issues/250)、
[251](https://github.com/scalamatsuri/2020.scalamatsuri.org/issues/251)について、open-source projectsについて修正の連絡あり。

メールの内容は[こちら](https://github.com/scalajp/2020.staff/issues/67#issue-558024018)

**Comment by Iwaji** [comment]
Kamil Klochさんの[281](https://github.com/scalamatsuri/2020.scalamatsuri.org/issues/281)、[282](https://github.com/scalamatsuri/2020.scalamatsuri.org/issues/282)について、削除依頼あり。
修正内容：削除

メールの内容は[こちら](https://github.com/scalajp/2020.staff/issues/68)

**Comment by taisukeoe** [comment]
上記のリクエストを、両方マスターに反映しました！
E28に追記
E37削除
