### ISSUE TITLE
Webロゴ掲載(奉行スポンサー：Sentry様)

### ISSUE THREAD

**Issue by YumiShibazaki** [scalamatsuri/2020.scalamatsuri.org#324]
- [x] リポジトリにロゴを入れる
- [x] 「nuxt_src/components/sections/top/sponsors.vue」を変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
'name': 'sentry',
'logo': '',
'url': 'https://sentry.io/',
'display_name': this.$i18n.t('bugyo_sentry')
 }
```
ロゴ画像:https://drive.google.com/open?id=1ou6lVh56pcpPD3AbByWqoG5aGvjz--03

**Comment by YumiShibazaki** [comment]
app_webチャンネルで話し合い、奉行名は「目付奉行/Metsuke-Bugyo」とすることにしました。

**Comment by tomoco95** [comment]
ref #325

**Comment by tomoco95** [comment]
掲載完了しました。
