### ISSUE TITLE
Webロゴ掲載(株式会社マイクロアド様)

### ISSUE THREAD

**Issue by YumiShibazaki** [scalamatsuri/2020.scalamatsuri.org#331]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "株式会社マイクロアド",
 "logo": "",
 "url": "https://www.microad.co.jp/"
}
```

ロゴ画像:https://drive.google.com/open?id=1hMThOHJAvuJYQWzsIDeebHIZ1zpBAYtI

**Comment by YumiShibazaki** [comment]
#338 , #339 にて掲載完了しました。

**Comment by YumiShibazaki** [comment]
マイクロアド様より、ロゴを差し替えてほしいとご連絡があったためreopenします。

**Comment by YumiShibazaki** [comment]
ロゴが20:7になっていなかったので調整しました。
調整後のロゴはこちら：https://drive.google.com/open?id=1odfofGXPa0lw33n9TtnZy85RMMKFWWpH

**Comment by YumiShibazaki** [comment]
#360 , #359 にて掲載完了しました。

ただ、ロゴ画像が綺麗に表示されない（白黒っぽい色味で表示されてしまう）場合があることが分かったため、原因を調査中です。
再度差し替え対応が必要になるかもしれないので、このIssueはopenのままにしておきます。

**Comment by YumiShibazaki** [comment]
高橋さんにIllustratorで再度サイズ調整してもらいました。
調整後のロゴはこちら：https://drive.google.com/open?id=1I-45y2v_Hn9bD_rl-LZH71zi2DUUv-Hz

調整後のロゴに差し替えてstaging環境で表示を確認しましたが、問題なさそうです。（ #361 ）
#362 がmasterにmergeされたらこのIssueはcloseします。

**Comment by tomoco95** [comment]
#362 がmergeされている事を確認しました。また、マイクロアドさんへロゴを差し替えた旨をご連絡しました。
