### ISSUE TITLE
Webロゴ掲載(株式会社サイバーエージェント様)

### ISSUE THREAD

**Issue by YumiShibazaki** [scalamatsuri/2020.scalamatsuri.org#337]
- [x] リポジトリにロゴを入れる
- [x]  jsonファイルを変更する
- [x]  develop branchに向けてPullRequestを送る
- [x]  staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x]  merge後、production環境のWebサイトに反映されていることを確認する

template:
```
,{
 "name": "株式会社サイバーエージェント",
 "logo": "",
 "url": "https://adtech.cyberagent.io/"
}
```
ロゴ画像:https://drive.google.com/open?id=1Y5QdE-pVfsT9bvSoOe-KiA6iybdf7L9-

**Comment by YumiShibazaki** [comment]
templateにあるURL：https://adtech.cyberagent.io/ が開けないため、サイバーさんに確認中。

**Comment by YumiShibazaki** [comment]
サイバーさんから連絡いただきました。
リンク先はこちら：https://cyberagent.ai/ に変更して欲しいとのことです。

また、ロゴの掲載についてはスポンサープランが確定するまで（詳細は[こちら](https://github.com/scalajp/2020.staff/issues/88#issuecomment-586820688) ）保留にして欲しいとのことなので、このIssueはopenのままにしておきます。

**Comment by tomoco95** [comment]
#407 staging環境へのPullRequestです

**Comment by YumiShibazaki** [comment]
#407 Mergeしました。
staging環境での表示も問題なさそうです！

**Comment by YumiShibazaki** [comment]
#408 master へのPullRequestです。

**Comment by tomoco95** [comment]
掲載完了し、サイバーさんへ連絡しました。
