### ISSUE TITLE
Webロゴ掲載(JapanTaxi株式会社様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#348]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "JapanTaxi株式会社",
 "logo": "",
 "url": "https://japantaxi.co.jp/recruit/"
}
```
ロゴ画像:https://drive.google.com/open?id=1hIhRGCeoDrGmw4WYWl7QJTA16w0SXIj3

**Comment by YumiShibazaki** [comment]
ロゴのサイズが20:7になっていなかったので調整しました。
調整後のロゴはこちら：https://drive.google.com/open?id=18rLnI1OPlkK58mb-ZU0Z8WDAxzej4kOg

**Comment by YumiShibazaki** [comment]
#357 , #359 にて掲載完了しました。
