### ISSUE TITLE
【4月1日以降の見込み】Webロゴの差し替え対応(株式会社Mobility Technologies様：旧JapanTaxi株式会社様) 

### ISSUE THREAD

**Issue by YumiShibazaki** [scalamatsuri/2020.scalamatsuri.org#350]
ref #348 

JapanTaxi株式会社様より下記の通りご連絡をいただいています。
```
ロゴとURLに関してですが、統合により4月1日から弊社の社名やロゴなどが変更になりますが、
現時点でJapanTaxiのロゴとURLを掲載した上で後から変更することは可能でしょうか？
```
「差し替え対応は可能」とお答えしてあるので、ご連絡いただき次第、差し替え対応を行います。

- [x] リポジトリのロゴを差し替える
- [x] （必要に応じて） jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

**Comment by tomoco95** [comment]
ロゴ・URLを差し替えることになりました。

新しいロゴ：
https://drive.google.com/file/d/1vKexN7Dx1QXdPl7E5Kqg7BwtZZ9zeomh/view?usp=sharing
新しい遷移先URL：https://mo-t.com/

**Comment by tomoco95** [comment]
ref #395

**Comment by tomoco95** [comment]
production環境への反映を確認して、Mobility Technologiesさんへ差替完了連絡をしました。
