### ISSUE TITLE
プロポーザル詳細ページのリンクのバグ

### ISSUE THREAD

**Issue by taisukeoe** [scalamatsuri/2020.scalamatsuri.org#355]
ref #354 

ja, en 共通の挙動。

https://scalamatsuri.org/ja/proposals

から、プロポーザルクリック => モーダルでタイトルクリック だと `https://scalamatsuri.org/ja/proposals/E35` などの独立ページ へ飛べる。

https://scalamatsuri.org/ja/proposals/

最後に `/` 入っていると、プロポーザルクリック => モーダルでタイトルクリック だとリンク先が `https://scalamatsuri.org/ja/proposals/proposals/E35` となり、独立ページ へ飛べない。

**Comment by taisukeoe** [comment]
なおナビゲーションから「プロポーザル一覧」をクリックした場合は `proposals` へ飛ばされるが、そのページでリフレッシュすると `proposals/` へ飛ばされる模様。

Google Chromeで確認。

**Comment by omiend** [comment]
ぐぬぬ、結構難敵かもしれませぬ。

**Comment by tkawachi** [comment]
https://scalamatsuri.org/ja からトークを選んで、タイトルをクリックすると https://scalamatsuri.org/proposals/E14 のようなリンクに飛んで not found になる。

**Comment by sugoikondo** [comment]
nuxt-linkとlocalePath 使ってれば起きなかった系のやーつでしたね

**Comment by tkawachi** [comment]
そうですね。 #454 で同時になおっている気がします。
