### ISSUE TITLE
Webロゴ掲載(株式会社アットウェア様)

### ISSUE THREAD

**Issue by YumiShibazaki** [scalamatsuri/2020.scalamatsuri.org#375]
- [x] リポジトリにロゴを入れる
- [x]  jsonファイルを変更する
- [x]  develop branchに向けてPullRequestを送る
- [x]  staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x]  merge後、production環境のWebサイトに反映されていることを確認する

template:
```
,{
 "name": "株式会社アットウェア",
 "logo": "",
 "url": "https://www.atware.co.jp/"
}
```
ロゴ画像:https://drive.google.com/open?id=1UXir3yqxYdkc1DHD7kdrn3gl2I1mTn08

**Comment by tomoco95** [comment]
本番環境に反映されてる事を確認して、SNS投稿とアットウェアさんへの連絡しました！
