### ISSUE TITLE
オンライン開催となったことを反映する

### ISSUE THREAD

**Issue by taisukeoe** [scalamatsuri/2020.scalamatsuri.org#409]
ref: https://blog.scalamatsuri.org/entry/2020/08/01/172639

- [ ] トップ画像(ja, en)
- [ ] OpenGraph画像(ja, en)
- [ ] ACCESS欄(ja, en)

**Comment by taisukeoe** [comment]
@sugoikondo 
ひとまず思いついたところを挙げてみましたが、他にどこかありましたっけ・・・？

**Comment by sugoikondo** [comment]
おそらく会場名とか周りはそれだけっぽい気がしました。

で、他のページでも

- [ ] Travelページ削除 (https://scalamatsuri.org/en/travel)
- [ ] 発表資料ページ オンライン開催に併せて要項修正 (https://scalamatsuri.org/ja/slides)
- [ ] (微妙ですが) スポンサーページ 募集要項変わったので修正？ (https://scalamatsuri.org/ja/sponsorship/)
- [ ] アンカンファレンスページ、どうするか (https://scalamatsuri.org/ja/unconference/)

的はずれな指摘でしたらアレですが、ここらへんもオンライン開催に併せて変える必要はありそうかなぁと思いました。
(正直アンカンファレンスページとか、今始めて知った感ありますが…)

**Comment by sugoikondo** [comment]
あと今は公開していないですが、敷いて挙げればスタッフ募集ページとかも変える必要あるかもですね…

ここらへんをどこまでを修正するか？はちょっとご意見伺いたいな…という感じです！

**Comment by taisukeoe** [comment]
@sugoikondo 
たしかに。ありがとうございます。Travel削除は要りますね。

> 発表資料ページ オンライン開催に併せて要項修正 (scalamatsuri.org/ja/slides)

は、最後のコネクタの話あたりはオンライン登壇の話に書き換えた方が親切かもですね。

> (微妙ですが) スポンサーページ 募集要項変わったので修正？ (scalamatsuri.org/ja/sponsorship)

はバックオフィスで別途対応します！ cc @tomoco95 

> アンカンファレンスページ

消すほどではないけど `obsolete`（最新ではないよ）って注釈は書いておきたいですね。

> スタッフ募集ページ

スタッフ募集は、やり方含めてぼちぼち決めないとですね。
とはいえ詳細決まってないので、一旦スコープ外で良い気がします！

**Comment by sugoikondo** [comment]
承知しました！そしたら、上で上げて頂いた3件プラスの、

- [ ] Travel非表示(404, リンク削除など) 
- [ ] スライド要項修正(ネット速度とか、マイクとか？ここらへん最低これはほしい！みたいなのまとまってましたっけ…) 

くらいを対応するで良さそうですね！

別件ですがこれくらいなら空き時間で対応すれば良さそうなので、集まって話する？みたいな機会、要らないかもですね…
サイト周りの話は、セッションやアンカンファレンス周りの話が固まってから本腰入れて、で良さそうかもなと思い始めてきました。。

**Comment by taisukeoe** [comment]
@sugoikondo 
すばらし 👍 
とすると、今わかってる重たい更新はあとタイムテーブルぐらいかな？って気がしますね！

**Comment by sugoikondo** [comment]
OGP, ちょっと元ファイル云々で色々あり新しく作成してみました。
没デザインのを踏襲したのですが、ダメそうでしたらご指摘頂けると助かります。

<img width="1317" alt="OGP" src="https://user-images.githubusercontent.com/16359063/89715306-b375d600-d9df-11ea-9398-deb026ea5f9b.png">

**Comment by taisukeoe** [comment]
@sugoikondo 
デザインシンプルで見やすいし、いい感じっぽいです！
一点、Scala Conference in Asiaだと、ちょっと意味が変わってそうな気がしますが、 `The largest Scala conference in Asia` はスペース的に厳しそうですかね。。。？

**Comment by sugoikondo** [comment]
こんな感じで如何でしょうか？
<img width="647" alt="OGP" src="https://user-images.githubusercontent.com/16359063/89774471-e71c4180-db40-11ea-996c-2f0c82807443.png">

ちなみにですが、WebサイトTOPの文字も同じく The largest ~ にしたいですよね。
ここ画像になっているのもアレなので、せっかくならsvg化するついでに文字も変えちゃおうかなと思っていますが、如何でしょうか？

**Comment by taisukeoe** [comment]
OGP良い感じだと思います！

そうか、そういえば現トップ画像もそんな感じの文字でしたね 😇 

![スクリーンショット 2020-08-10 20 42 22](https://user-images.githubusercontent.com/1506707/89779315-053a6f80-db4a-11ea-9f18-693dff36ad04.png)

> せっかくならsvg化するついでに文字も変えちゃおうかな

素敵だと思います 👍

**Comment by sugoikondo** [comment]
こんな感じにしますね
| en | ja |
|-----|-----|
| <img width="404" alt="ScalaMatsuri_2020___The_largest_international_Scala_conference_in_Asia" src="https://user-images.githubusercontent.com/16359063/89781247-edfd8100-db4d-11ea-9aee-4f0ff710202c.png"> | <img width="371" alt="ScalaMatsuri_2020___アジア最大級の_Scala_のカンファレンス" src="https://user-images.githubusercontent.com/16359063/89781274-fa81d980-db4d-11ea-9046-b80b4c32d6f8.png"> |
| <img width="976" alt="ScalaMatsuri_2020___The_largest_international_Scala_conference_in_Asia" src="https://user-images.githubusercontent.com/16359063/89781365-21401000-db4e-11ea-92b6-ca811bd574a4.png"> | <img width="989" alt="ScalaMatsuri_2020___アジア最大級の_Scala_のカンファレンス" src="https://user-images.githubusercontent.com/16359063/89781331-16857b00-db4e-11ea-9d13-50604942b967.png"> |

**Comment by taisukeoe** [comment]
配置はいいですね 👍 

at onlineって表現はあまり見ないかも。
atつけないか、そもそもトップ画像に `online` って表記入れる必要な気もしてきました。

**Comment by sugoikondo** [comment]
確かに、オンラインの文言自体消してしまって良さそうですね。修正します！
