### ISSUE TITLE
Webロゴ掲載(株式会社COMPASS様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#426]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "",
 "logo": "",
 "url": "https://qubena.com/"
}
```

ロゴ画像:https://drive.google.com/open?id=1JLTphqEi-6IND18FQneHDt41S2NmQHLl

**Comment by YumiShibazaki** [comment]
#427 にて開発環境へ反映済み。
#428 でMasterへPull requestを出しました。

**Comment by tomoco95** [comment]
#431 でmasterに反映済みです。私のほうで表示確認しておきました。
