### ISSUE TITLE
Webロゴ掲載(レバレジーズ株式会社様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#451]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "",
 "logo": "",
 "url": "https://leverages.jp"
}
```
ロゴ画像:https://drive.google.com/open?id=1d8J0rdzL0pdcPn10gwtd4bZ9Yezma37L

**Comment by YumiShibazaki** [comment]
ロゴサイズを調整しました。
https://drive.google.com/file/d/1NYpQjphqMeKoc4DHkhYik2jB-_iLhYyn/view?usp=sharing

**Comment by tomoco95** [comment]
#457 でmasterに反映

**Comment by tomoco95** [comment]
掲載の確認・連絡しました！
