### ISSUE TITLE
Webロゴ掲載(Scalapedia・合同会社ミルクソフト様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2020.scalamatsuri.org#460]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "",
 "logo": "",
 "url": "https://scalapedia.com"
}
```
ロゴ画像:https://drive.google.com/file/d/1BTrvX93vB4fzsGB0AtPkuSNT6LdHesqB/view?usp=sharing

**Comment by YumiShibazaki** [comment]
#463 でmasterへPull requestを出しました。

**Comment by tomoco95** [comment]
掲載と連絡完了しました
