### ISSUE TITLE
Sponsorshipページを募集案内とフォームが用意され次第公開する

### ISSUE THREAD

**Issue by sugoikondo** [scalamatsuri/2020.scalamatsuri.org#68]
mixinとして定義されているPage404NotFoundを削除すれば公開される。

募集案内のpdfと応募フォームが用意され次第、公開を行う。

**Comment by omiend** [comment]
削除する行
https://github.com/scalamatsuri/2020.scalamatsuri.org/blob/master/nuxt_src/pages/sponsorship/index.vue#L291

https://github.com/scalamatsuri/2020.scalamatsuri.org/blob/master/nuxt_src/pages/sponsorship/index.vue#L293-L294

**Comment by omiend** [comment]
こちらも対応すること
https://github.com/scalamatsuri/2020.scalamatsuri.org/issues/69
