### ISSUE TITLE
ログイン機能実装まで、ヘッダのログインボタンをスポンサー募集ボタンにしておく

### ISSUE THREAD

**Issue by sugoikondo** [scalamatsuri/2020.scalamatsuri.org#70]
ヘッダのボタンはその都度表示を変更する可能性あり。
(スポンサー募集が少ない特はスポンサー募集、CFPが少ないときはCFPのボタンを表示するなど。)

![スクリーンショット_2019_11_21_20_18](https://user-images.githubusercontent.com/16359063/69333520-1c73bd00-0c9c-11ea-967a-38c1d57477e9.png)

**Comment by sugoikondo** [comment]
ヘッダ内にスポンサーへのリンクがあるため、これで良いのでは？
あるいはこちらを削除して右のボタンにするか？

![ScalaMatsuri_2020___アジア最大級の_Scala_のカンファレンス](https://user-images.githubusercontent.com/16359063/70917488-c73f8700-2060-11ea-91b1-27c9946c38ef.png)

**Comment by taisukeoe** [comment]
CFP closeから投票開始までそんなに間もあかないので、やめときましょう〜
