### ISSUE TITLE
検証環境を用意する

### ISSUE THREAD

**Issue by sugoikondo** [scalamatsuri/2020.scalamatsuri.org#75]
投票機能のテスト検証にも使えるので、検証環境が必要かもしれない。

**Comment by omiend** [comment]
## やること

- develop ブランチを作成する
- デフォルトのブランチを develop にする
- develop にマージされたら検証環境にデプロイするように GitHub Actions を設定する
- master ブランチへの直接のプッシュは出来ないようにする

## 確認したいこと
-[ ] 本番と検証環境の呼び方
  - 本番: Production / 検証: Staging で良いか？
- [ ] 本番環境へのデプロイに利用している GitHub Actions の yaml の名前（ deploy.yaml ）はとりあえずこのままでよいか？
  - deployProduction.yaml / deployStaging.yaml みたいにしたほうが良さそう？

**Comment by omiend** [comment]
Auth のテストで使ってもらうので、下記は一旦対応しない。

-  デフォルトのブランチを develop にする
-  master ブランチへの直接のプッシュは出来ないようにする

**Comment by omiend** [comment]
master向けに PR 作ったので Close します。
https://github.com/scalamatsuri/2020.scalamatsuri.org/pull/95
