### ISSUE TITLE
投票機能の作成

### ISSUE THREAD

**Issue by sugoikondo** [scalamatsuri/2020.scalamatsuri.org#80]
memo: Issueを分ける

### 投票フロー

* Loginする
  * チケット購入後の購入番号なりを入力する(投票の前後どこでやるかは未定)
* プロポーザル一覧からMax5つ(N個)選ぶ
  * 順位づけができる
  * Drag & Dropで動かせる
* 状態を保存する

**Comment by sugoikondo** [comment]
PRでResolvesに間違えて追加してしまった感じですかね？まだ実装していない(実装中)なので再度Openします。

**Comment by taisukeoe** [comment]
# 投票関連機能
## 認証
- [ ] Loginできる
- [ ] チェックインコードを入力し、保存できる

## 投票
- [ ] プロポーザル一覧で、Max5つ選んで投票できる
- [ ] 投票したプロポーザルを順位づけできる
  -  [ ] Drag & Dropで動かせる
- [ ] 投票結果の状態が保存できて、同一ユーザーが編集できる

## 投票補助
- [ ] プロポーザル一覧で、個数制限なく選んで保存できる（お気に入り）
- [ ] カテゴリでフィルターできる
- [ ] 個々のプロポーザルのパーマリンクを発行する #207

## 投票終了
-  [ ] 投票および投票内容の変更をできなくする #81 
-  [ ] 集計スクリプトの動作確認・修正 ref https://github.com/scalajp/2019.staff/pull/194

**Comment by sugoikondo** [comment]
> 投票結果の状態が保存できて、同一ユーザーが編集できる
アプリ側から登録できること以外に、エミュレータから『認証していない場合は情報の取得・更新ができないこと』『認証済みであってもidが異なる equals 別ユーザのっ場合は取得・更新ができないこと』は確認。

**Comment by sugoikondo** [comment]
> 集計スクリプトの動作確認・修正 ref scalajp/2019.staff#194?
一票の格差的な問題は今回は考慮しない(重み付けはしない)とのことだったので、自分で適当にスクリプトを書いて単純に有効表だけを合算するスクリプトを書くかも
